### ISSUE TITLE
android uav status is alive even though the drone card cell phone is turned off

### ISSUE THREAD

**Issue by orangefabri** [HefnySco/andruav_android_app#10]
android UAV status is alive on GCS even though the drone card cell phone is turned off.

**Comment by orangefabri** [comment]
maybe it is related to korean government policy. some of maps are restricted in korea, as far I know.

**Comment by HefnySco** [comment]
it should be offline after less than a minute. WebClient display units as -offline- when receiving no data from them after few seconds.
