### ISSUE TITLE
there is no docs about connecting mission planner via UDP

### ISSUE THREAD

**Issue by orangefabri** [HefnySco/andruav_android_app#11]
![IMG_0551](https://user-images.githubusercontent.com/103094244/227757145-bd02aae5-5089-4f38-99e8-8dd940661969.jpg)

this is my GCS tablet screen.

telemetry connection is well estabilished.

both mission planner laptop and GCS tablet are on same network.

and I tried that ip address and port via UDPCL, UDP, TCP, AUTO on mission planner.

but couldn't make connection on mission planner.

**Comment by HefnySco** [comment]
Please check these videos:
[https://youtu.be/C_AcmUGXFVQ](https://youtu.be/C_AcmUGXFVQ)
[https://youtu.be/jOeL0XXYoME](https://youtu.be/jOeL0XXYoME)

and generally this playlist [https://www.youtube.com/playlist?list=PLbv12w8pMoMOmAYVTEYNM1JGFH8DyG3th](https://www.youtube.com/playlist?list=PLbv12w8pMoMOmAYVTEYNM1JGFH8DyG3th)

**Comment by orangefabri** [comment]
I was able to solve the problem after switching to the web client. This issue can now be considered resolved. Thank you for your assistance!

**Comment by Jai-GAY** [comment]
Hi @orangefabri 

How did you able to get the Android Ground unit to list the telemetry for selection? mine is an empty list.
I can see both the Android Andruav drone and Ground units shown in the web client browser.
Which Andruav version did you use?

**Comment by HefnySco** [comment]
This feature is obsolete. Now you can use UDP connect from Mission Planner
to server directly which is alot faster.
https://cloud.ardupilot.org/webclient-udp-telemetry.html

As you can see in the image below. The udp connection is mentioned on the
drone mobile.

**Comment by Jai-GAY** [comment]
@HefnySco 

Thanks, noted. by the way, what is this icon means in the attached image?

![IMG_20230516_100806_sm](https://github.com/HefnySco/andruav_android_app/assets/12781023/dbec60e0-d84e-45dd-8921-a761a7572332)

**Comment by HefnySco** [comment]
This icon enables 4g with wifi to speed up connection. It depends on mobile
model.
