### ISSUE TITLE
Java 11 & API > 30

### ISSUE THREAD

**Issue by Jai-GAY** [HefnySco/andruav_android_app#14]
Does anyone encounter this when trying to compile the code?

> A problem occurred evaluating project ':andruavmiddlelibrary'.
> Failed to apply plugin 'com.android.internal.library'.
   > [Android Gradle plugin requires Java 11 to run.](https://docs.gradle.org/current/userguide/compatibility.html) You are currently using Java 1.8.

[JCenter service update](https://developer.android.com/build/jcenter-migration)
https://github.com/HefnySco/andruav_android_app/blob/3c968ae342686c4d646d9dd9c9278edcc3bdfe7e/build.gradle#L49

[Suspicious indentation](https://github.com/HefnySco/andruav_android_app/blob/3c968ae342686c4d646d9dd9c9278edcc3bdfe7e/app/src/main/java/ap/andruav_ap/App.java#L470)
![image](https://github.com/HefnySco/andruav_android_app/assets/12781023/a9f62ebc-3f01-407f-b534-73f2f23696bb)

potential duplicate class conflict with Kotlin (org.jetbrains:annotations)https://github.com/HefnySco/andruav_android_app/blob/3c968ae342686c4d646d9dd9c9278edcc3bdfe7e/webrtc/build.gradle#L46

Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 20, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
Non-Bundled Plugins:
    org.intellij.plugins.markdown (222.4345.5)

**Comment by Jai-GAY** [comment]
> A problem occurred evaluating project ':andruavmiddlelibrary'.

I solve it by changing the following two lines to **sourceCompatibility JavaVersion.VERSION_11** and **targetCompatibility JavaVersion.VERSION_11**
https://github.com/HefnySco/andruav_android_app/blob/3c968ae342686c4d646d9dd9c9278edcc3bdfe7e/andruavmiddlelibrary/build.gradle#L46
https://github.com/HefnySco/andruav_android_app/blob/3c968ae342686c4d646d9dd9c9278edcc3bdfe7e/andruavmiddlelibrary/build.gradle#L47


> potential duplicate class conflict with Kotlin (org.jetbrains:annotations)

I solve it by changing the following line to **implementation 'org.jetbrains:annotations:13.0'**
https://github.com/HefnySco/andruav_android_app/blob/3c968ae342686c4d646d9dd9c9278edcc3bdfe7e/webrtc/build.gradle#L46

**Comment by Jai-GAY** [comment]
[will get the following crash if target API >= 31](https://developer.android.com/reference/android/os/Build.VERSION_CODES#S)
need to upgrade the [d2xx.jar library](https://github.com/HefnySco/andruav_android_app/tree/master/ClientLib/libs) to [version 2.10](https://ftdichip.com/software-examples/android-java-d2xx/). Also, various calls must include PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_MUTABLE flag upon Build.VERSION.SDK_INT check

Process: arudpilot.andruav, PID: 6900
java.lang.IllegalArgumentException: arudpilot.andruav: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:402)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:672)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:659)
	at com.ftdi.j2xx.D2xxManager.updateContext(D2xxManager.java:767)
	at com.ftdi.j2xx.D2xxManager.<init>(D2xxManager.java:799)
	at com.ftdi.j2xx.D2xxManager.getInstance(D2xxManager.java:827)
	at org.droidplanner.services.android.impl.communication.connection.usb.UsbFTDIConnection.openUsbConnection(UsbFTDIConnection.java:29)
	at org.droidplanner.services.android.impl.communication.connection.usb.UsbConnection.openConnection(UsbConnection.java:64)
	at org.droidplanner.services.android.impl.core.MAVLink.connection.MavLinkConnection$1.run(MavLinkConnection.java:90)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Jai-GAY** [comment]
[Suggestions and modifications are done.](https://github.com/HefnySco/andruav_android_app/commit/4e3e10aa56df326b393276a47d4120f35aed8a9d)

**Comment by HefnySco** [comment]
Would you make a PR to join it to code please.

**Comment by Jai-GAY** [comment]
Sorry, I just started using Github I am not sure how to Pull Requests via my forked repository.

**Comment by HefnySco** [comment]
on your branch it should it ask you if you want to merge to main repository
via pr... just a click on a button.

**Comment by Jai-GAY** [comment]
[Submitted](https://github.com/HefnySco/andruav_android_app/pull/21), hope I am correct in the procedure.
