### ISSUE TITLE
CheckAppPermissions.checkPermissionAndRequest

### ISSUE THREAD

**Issue by Jai-GAY** [HefnySco/andruav_android_app#17]
Is there contains a logic error for this logic check?

https://github.com/HefnySco/andruav_android_app/blob/3c968ae342686c4d646d9dd9c9278edcc3bdfe7e/app/src/main/java/ap/andruav_ap/helpers/CheckAppPermissions.java#L54

when PackageManager.PERMISSION_GRANTED it will return true yet it goes into the if statement to request for permission.
https://github.com/HefnySco/andruav_android_app/blob/3c968ae342686c4d646d9dd9c9278edcc3bdfe7e/app/src/main/java/ap/andruav_ap/helpers/CheckAppPermissions.java#L46

So, the check should be this way, right, missing !? 
if ( **!** checkPermission(activity,permission))

Note: If your app targets [Build.VERSION_CODES.R](https://developer.android.com/reference/android/os/Build.VERSION_CODES#R) or higher, [WRITE_EXTERNAL_STORAGE permission has no effect.](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE)

**Comment by Jai-GAY** [comment]
[Suggestions and modifications done](https://github.com/HefnySco/andruav_android_app/commit/4e3e10aa56df326b393276a47d4120f35aed8a9d).

**Comment by HefnySco** [comment]
@Jai-GAY please email me on mohammad.hefny@gmail.com
I need your help in Andruav.
O am targeting to add SMS and I need your support to update permission proberly.
The idea is to use SMS to report location in case of emergency and to use SMS to activate RTL in case of signal loss.
