### ISSUE TITLE
Connection issues and enhancements

### ISSUE THREAD

**Issue by rmackay9** [HefnySco/andruav_android_app#2]
During testing I've turned up a few issues that (if resolved) would make it easier to use:

- [x] #5
- [x] #4
- [x] #6
- [x] #3

**Comment by HefnySco** [comment]
> During testing I've turned up a few issues that (if resolved) would make it easier to use:
> 
> * [x]  On the FCB page's menu there is an "Auto Connect FCB" check box but this doesn't seem to work.  I assume checking this should make the Andruav AP app automatically connect to the flight controller when opened.

**Done.** 

> * [ ]  On the FCB page, after pushing the connect triangle, "Allow the app Andruav-AP to access the USB device?" along with a "Use by default for this USB device?" checkbox.  This pop-up always appears but it would be nice if I didn't need to permission it each time.

**_It appears on some mobiles, and not consistent. I could not solve it 100%._**

> * [x]  If after the above, I reject permissions (by pressing "Cancel") a message, "Link Connection: FAILED" appears but the green triangle still turns green.  So it has not connected but it incorrectly shows that it has.

**Connect Button in FCB activity has three states now "Gray, Blue & Green" to distinguish from connecting & successfully connected.**

> * [x]  It would be nice if there were a way to automatically connect to the internet after the application starts instead of forcing the user to push the connect button

**Yes this feature is already available.** please check this [https://youtu.be/Zyx1mzqCYP0](https://youtu.be/Zyx1mzqCYP0)

**Comment by HefnySco** [comment]
> * [x]  On the FCB page, after pushing the connect triangle, "Allow the app Andruav-AP to access the USB device?" along with a "Use by default for this USB device?" checkbox.  This pop-up always appears but it would be nice if I didn't need to permission it each time.


DONE
