### ISSUE TITLE
It would be nice if there were a way to automatically connect to the internet after the application starts instead of forcing the user to push the connect button

### ISSUE THREAD

**Issue by HefnySco** [HefnySco/andruav_android_app#3]

**Comment by HefnySco** [comment]
This function already exists in Andruav/WebClient.
I made this video that shows how to do it:

https://youtu.be/Zyx1mzqCYP0

**Comment by rmackay9** [comment]
Hi thanks,  I think there's a small misunderstanding perhaps.  So what I mean is that it would be nice if I didn't need to push this connection button (the one that connects the app to the internet).  It's not a big deal but I'm thinking it would be nice to reduce the number of steps a user must go through to get the system up and running each time.
![image](https://user-images.githubusercontent.com/1498098/178192274-313121cf-20ed-4af8-bb3c-206e4186e237.png)

**Comment by HefnySco** [comment]
Please check 
[https://youtube.com/shorts/QpBwPJ3Cl1E?feature=share](https://youtube.com/shorts/QpBwPJ3Cl1E?feature=share)
I think what are you looking for is Auto_Start.

**Comment by rmackay9** [comment]
@HefnySco,

Ah, great, thanks.  I somehow missed that checkbox.  I think we can close this issue now.

By the way, I found some unreliability if Andruav app is not running when I plug in the USB cable to the flight controller.  The Andruav app sometimes crashes, appears as a blank screen or it fails to connect to the flight controller.  The behaviour is not consistently the same so I suspect it has something to do with timing and whether the autopilot is ready to communicate or not.
