### ISSUE TITLE
On the FCB page, after pushing the connect triangle, "Allow the app Andruav-AP to access the USB device?" along with a "Use by default for this USB device?" checkbox.  This pop-up always appears but it would be nice if I didn't need to permission it each time.

### ISSUE THREAD

**Issue by HefnySco** [HefnySco/andruav_android_app#4]

**Comment by HefnySco** [comment]
This is not consistent in all mobiles. But it sometimes occurs.

**Comment by rmackay9** [comment]
This seems better for me somehow.  In the latest version it seems that Andruav app is starting automatically whenever I plug in the USB connection to the FCB.  I'm happy with this being closed now but up to you.  Txs!

**Comment by rmackay9** [comment]
This seems fixed for me now. txs!
