### ISSUE TITLE
On the FCB page's menu there is an "Auto Connect FCB" check box but this doesn't seem to work.  I assume checking this should make the Andruav AP app automatically connect to the flight controller when opened.

### ISSUE THREAD

**Issue by HefnySco** [HefnySco/andruav_android_app#5]

**Comment by HefnySco** [comment]
fixed in version 5.00.14

**Comment by rmackay9** [comment]
Ok thanks.  This doesn't quite work for me it seems.

This is what happens:

- I plug in the USB port.  Andruav app is started automatically (this is new for me and a good thing).
- the big "FCB" button is Blue (not green).  If I push the FCB button I see the triangle is grey.  If I push the triangle it connects and turns green.
- if I restart Andruav (leaving the USB connected) then the big "FCB" button is green this time.  If I push the FCB button I see that the triangle is actually grey (not green like it probably should be).  If I push the triangle it says "Disconnecting" and stalls for a long time.
