### ISSUE TITLE
If after the above, I reject permissions (by pressing "Cancel") a message, "Link Connection: FAILED" appears but the green triangle still turns green.  So it has not connected but it incorrectly shows that it has.

### ISSUE THREAD

**Issue by HefnySco** [HefnySco/andruav_android_app#6]

**Comment by HefnySco** [comment]
Connect Button in FCB activity has three states now "Gray, Blue & Green" to distinguish from connecting & successfully connected.
The FCB button in the home page is the button that tells if there is a valid connection or not based on its color green or blue respectively. It also can be RED if in block mode.

**Comment by rmackay9** [comment]
Txs for this.  I very much like the three states!
