### ISSUE TITLE
Video connection problem on a GCS app.

### ISSUE THREAD

**Issue by orangefabri** [HefnySco/andruav_android_app#8]
Hello,

I would like to use this app and potentially support the development of this complex application in the future if I can learn this code structure. Specifically, I am interested in improving the ardupilot's capabilities for use on a maritime drone.

However, I have encountered a problem with this app. When I click the "Video" button on the GCS app, it always displays "Video is connecting" but fails to connect. I installed this app yesterday, it is first time I'm using this app. however, this app was used yesterday for 5 minutes flying, so I don't believe it's a problem with my settings. Yesterday, I also had trouble with the "Video is connecting" message consistently displaying on the screen.

for your reference, telemetry is connecting properly, and I was able to hear the "PreArm: Throttle below failsafe" message on both the GCS and drone card. Additionally, I am able to successfully receive photos from the drone card when I press the "shoot" button on the GCS, so I don't believe it's a connection issue.

I have tried using a mobile hotspot, public wifi, and a portable wifi router that worked well for video streaming on other GCS. Therefore, I don't believe it's a problem with the connection speed.

The only issue seems to be that the video is not connecting now. I tried "ask for help" button but there is no log file automatically attached.

**Comment by orangefabri** [comment]
I tried turning off HD options in drone card, but not worked.

I want to modify docs later for more information to be included.

**Comment by orangefabri** [comment]
for your reference, I can even swap drone's camera on GCS app.

**Comment by orangefabri** [comment]
I also changed android's battery optimization and network optimization settings, but nothing changed.

**Comment by orangefabri** [comment]
and I have no anti-virus app on my drone card. there is no security app on drone card.

**Comment by orangefabri** [comment]
I turned on send anonymous anlaysis to server and logging option.

**Comment by HefnySco** [comment]
> I tried turning off HD options in drone card, but not worked.
> 
> I want to modify docs later for more information to be included.

Did you try to use [WebClient](https://cloud.ardupilot.org:8001/webclient.html)

**Comment by HefnySco** [comment]
I am not investing effort in Andruav GCS, as you can use WebClient to make the same functionalities.

**Comment by orangefabri** [comment]
> I am not investing effort in Andruav GCS, as you can use WebClient to make the same functionalities.

Thank you for your reply. I thought this application concept is great. anyway, I have to test connectivity of phone's modem at sea first. after that I can decide whether to use phone for LTE communication.
after the test I will try this app. thank you.

**Comment by orangefabri** [comment]
> I am not investing effort in Andruav GCS, as you can use WebClient to make the same functionalities.

I tried webclient as you adviced.

but the video screen still blank.

it seems that there are some problem on my connection.

other function worked well(I turned on and off the flash light)

https://drive.google.com/file/d/1AXdtwUX09af47XC-_MmYYWnD5OnxFtt7/view?usp=share_link

sorry for frequent questions.

**Comment by orangefabri** [comment]
After connecting to Mission Planner, I realized that this proejct was a great concept with limitless expandability, and I became very interested in it. I was curious about how it works I just entered "andruav.com" as the host name and "41988" as the port name on the Mission Planner UDPCL connection, and it just worked!

I was surprised that it worked with just a simple URL entry. I found a video (https://cloud.ardupilot.org/webclient-udp-telemetry.html) where you connected to "192.xx.xxx.xx," so I thought I needed to establish an internal server connection with a special tool. However, it turned out that I didn't need to do that.

I'm still curious about how the website can pass data to Mission Planner automatically. Specifically, I wonder how It can distinguish my connection from that of other users on other laptops worldwide. There could be other people who type in the same URL "andruav.com."

**Comment by HefnySco** [comment]
Regarding telemetry please refer to this video for more details[https://youtu.be/C_AcmUGXFVQ]( https://youtu.be/C_AcmUGXFVQ)

**Comment by HefnySco** [comment]
Please feel free to ask. BTW I have just retested now the video over LTE to make sure that my phone is not using my home wifi and I could receive the video from the mobile.

**Comment by orangefabri** [comment]
If these operations in daily basis require a lot of traffic on the ArduPilot server, I am willing to use my existing AWS server instead.

**Comment by orangefabri** [comment]
> Please feel free to ask. BTW I have just retested now the video over LTE to make sure that my phone is not using my home wifi and I could receive the video from the mobile.

Here is the video link that describes the symptom. Unfortunately, I have been unable to connect to the web client. Therefore, I uploaded the video using the Andruav GCS app. As you can see in the video, taking photos is possible, but the video does not come through. I have tried different networks, but the issue persists.

If I cannot solve this problem, I am considering creating a server and app based on your code. However, I anticipate that this will be a difficult and long-long time task.

https://drive.google.com/file/d/1DiGmMcfWaSfw9yIDuRGQD6G0Ph3Bawqo/view?usp=share_link

**Comment by orangefabri** [comment]
> Please feel free to ask. BTW I have just retested now the video over LTE to make sure that my phone is not using my home wifi and I could receive the video from the mobile.

I've discovered that I can't connect to 'cloud.ardupilot.org:8001/webclient.html' through Safari. Is this normal, or could it be an issue with my internet carrier?

**Comment by HefnySco** [comment]
> > Please feel free to ask. BTW I have just retested now the video over LTE to make sure that my phone is not using my home wifi and I could receive the video from the mobile.
> 
> I've discovered that I can't connect to 'cloud.ardupilot.org:8001/webclient.html' through Safari. Is this normal, or could it be an issue with my internet carrier?

WebClient is developed for Chrome & FireFox. Never tested it on Safari or Edge.

**Comment by HefnySco** [comment]
BTW I can help you to create your own server on aws.
please contact me mohammad.hefny@gmail.com

**Comment by orangefabri** [comment]
I attempted to access 'cloud.ardupilot.org:8001/webclient.html' on my friends' iPad and iPhone, but it was unsuccessful. I am uncertain if this is due to a network or iOS issue. If it were in America, I suspect it would be able to connect.

**Comment by orangefabri** [comment]
> BTW I can help you to create your own server on aws. please contact me [mohammad.hefny@gmail.com](mailto:mohammad.hefny@gmail.com)

Earlier, I shared with you a video that demonstrated the failure of the "andruav_ap" app. Now, I would like to share another video link that demonstrates the issue of failed connections on "webclient.html". :

https://drive.google.com/file/d/1A9_j_X-C6GUc70EOzcLVJFCSMW93vwR6/view?usp=share_link

As you can see in the video, the telemetry connection (drone's attitude) is alive, but the video is dead. When I first installed the app, I was able to get the videos to work, but only for 5 minutes flying.

and there is another problem for your reference. whenever I click the recording button on the web client or touch the recording button on the Andruav_ap app, the drone card app resets the connection (lost connection once) and fails to record.

I will send you an email with the details on using my AWS server to transfer the video and telemetry data. Thank you.

**Comment by orangefabri** [comment]
> BTW I can help you to create your own server on aws. please contact me [mohammad.hefny@gmail.com](mailto:mohammad.hefny@gmail.com)

also, I noticed that the Chrome mobile app on Android was unable to connect to "https://cloud.ardupilot.org:8001/webclient.html". Is it only possible to connect from a desktop for now? during ship delivery, we are now need to move to take-off locations where mobile phone may be the easiest option to use. we didn't have static stations yet. However, for now, a desktop connection is sufficient. I will email you to establish a connection on my own AWS server. Thank you.

**Comment by HefnySco** [comment]
I think we need to conduct a video session. I can help you with this. The system is easy to work.

**Comment by orangefabri** [comment]
It turns out that the reason for the connection failure on Safari or Mobile Chrome was due to the missing 'https://' in the address. now I can connect on mobile well.
However, I am still unable to connect to the video.

Thank you for suggesting a video session, but for now, I am using ChatGPT to refine my grammar and expressions. While I may not be proficient in English, I can do basic conversations without elegant expressions.

and I'm very glad to hear that the work is straightforward.
I am currently using an EC2 t2 micro instance, which has limited resources (1GB RAM and moderate network performance). If it turns out to be insufficient during the actual UAV test, I will switch to a higher-class AWS Instance.

**Comment by orangefabri** [comment]
> I think we need to conduct a video session. I can help you with this. The system is easy to work.

It's been a while now, and I'm still unable to receive videos. I've tried to regenerate my access code using my email [sseaeagle2@gmail.com], but I haven't received anything in my inbox including spam folder. I've tried on both my laptop and cell phone.

I suspect I may have requested the code too many times before. I tried about 10 times previously because something wasn't working and I couldn't get the code.

Could you please confirm whether I've been banned from the server?

**Comment by orangefabri** [comment]
> I think we need to conduct a video session. I can help you with this. The system is easy to work.

I was able to generate a code using my other email account. However, the code is only visible within the app and did not arrive in my email inbox. The pop-up message stated that the access code was also sent by email, but I have not received it.

**Comment by orangefabri** [comment]
> I think we need to conduct a video session. I can help you with this. The system is easy to work.

I successed to connect video once. I regenerated code with my other email, and click "FPV" button on the cell phone, after that, I clicked "live stream" on laptop twice.
only click "live stream" twice or third time not works. it is my weird solution, hard to found.

but, now it is not connected again.

**Comment by HefnySco** [comment]
sorry but you said you cannot login to [cloud.ardupilot.org:8001/webclient.html](https://cloud.ardupilot.org:8001/webclient.html)

Thank means you have a severe connection problem. If you cannot see the website you will not be able to do anything.

use airgap ... download latest version and change the turnserver addresses.

**Comment by HefnySco** [comment]
> > BTW I can help you to create your own server on aws. please contact me [mohammad.hefny@gmail.com](mailto:mohammad.hefny@gmail.com)
> 
> also, I noticed that the Chrome mobile app on Android was unable to connect to "https://cloud.ardupilot.org:8001/webclient.html". Is it only possible to connect from a desktop for now? during ship delivery, we are now need to move to take-off locations where mobile phone may be the easiest option to use. we didn't have static stations yet. However, for now, a desktop connection is sufficient. I will email you to establish a connection on my own AWS server. Thank you.

AndruavAP connects to Communcation Server. and you need to use the same account to access your mobile from webclient.

**Comment by orangefabri** [comment]
> sorry but you said you cannot login to [cloud.ardupilot.org:8001/webclient.html](https://cloud.ardupilot.org:8001/webclient.html)
> 
> Thank means you have a severe connection problem. If you cannot see the website you will not be able to do anything.
> 
> use airgap ... download latest version and change the turnserver addresses.

I can login with other mail account. I can see websites. but every email account cannot regenerate code.

I will try airgap, thank you

**Comment by orangefabri** [comment]
> > > BTW I can help you to create your own server on aws. please contact me [mohammad.hefny@gmail.com](mailto:mohammad.hefny@gmail.com)
> > 
> > 
> > also, I noticed that the Chrome mobile app on Android was unable to connect to "https://cloud.ardupilot.org:8001/webclient.html". Is it only possible to connect from a desktop for now? during ship delivery, we are now need to move to take-off locations where mobile phone may be the easiest option to use. we didn't have static stations yet. However, for now, a desktop connection is sufficient. I will email you to establish a connection on my own AWS server. Thank you.
> 
> AndruavAP connects to Communcation Server. and you need to use the same account to access your mobile from webclient.

this problem already solved as I said above. attaching Https:// in address solved the problem

**Comment by orangefabri** [comment]
> Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.

Im using cell phone instead of RPI4... if I have to use RPI4, I will rather use jetson board

**Comment by orangefabri** [comment]
> sorry but you said you cannot login to [cloud.ardupilot.org:8001/webclient.html](https://cloud.ardupilot.org:8001/webclient.html)
> 
> Thank means you have a severe connection problem. If you cannot see the website you will not be able to do anything.
> 
> use airgap ... download latest version and change the turnserver addresses.

all the error message I attahced is related to video button. I can see website.

**Comment by orangefabri** [comment]
> > > BTW I can help you to create your own server on aws. please contact me [mohammad.hefny@gmail.com](mailto:mohammad.hefny@gmail.com)
> > 
> > 
> > also, I noticed that the Chrome mobile app on Android was unable to connect to "https://cloud.ardupilot.org:8001/webclient.html". Is it only possible to connect from a desktop for now? during ship delivery, we are now need to move to take-off locations where mobile phone may be the easiest option to use. we didn't have static stations yet. However, for now, a desktop connection is sufficient. I will email you to establish a connection on my own AWS server. Thank you.
> 
> AndruavAP connects to Communcation Server. and you need to use the same account to access your mobile from webclient.

of course, Im using same account. it is too basic thing. the question was, cant connect to web client via safari, and the reason was not attaching https:// on address, as I said before

**Comment by orangefabri** [comment]
> Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.

could I know the airgap server's basic meaning? could I run it on aws server, with similar way for RPI4?

**Comment by HefnySco** [comment]
> > Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> > Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.
> 
> could I know the airgap server's basic meaning? could I run it on aws server, with similar way for RPI4?

yes you can.
you need aws machine with a domain and that is it.

**Comment by orangefabri** [comment]
> > > Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> > > Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.
> > 
> > 
> > could I know the airgap server's basic meaning? could I run it on aws server, with similar way for RPI4?
> 
> yes you can. you need aws machine with a domain and that is it.

I already made domain with name, but, installation instruction says domain name is "http://airgap.droneengage.com/".

is there way to edit the scritps..?

I'm also worrying about it is aws linux 2..

https://raw.githubusercontent.com/HefnySco/andruav_droneengane_scripts/main/server_installation/prepare-airgapped-server.sh

this is your script for raspberry pi..

**Comment by orangefabri** [comment]
> > > Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> > > Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.
> > 
> > 
> > could I know the airgap server's basic meaning? could I run it on aws server, with similar way for RPI4?
> 
> yes you can. you need aws machine with a domain and that is it.

I tried install your scripts on AWS linux 2 at first, but found "sudo apt-get" command will not work and there is no easy way to install "coturn" with AWS linux 2.

so I changed my AWS instance to ubuntu OS, and tried your script.

this is the result of the script. it seems something goes wrong :

[ubuntu log.txt](https://github.com/HefnySco/andruav_android_app/files/11209379/ubuntu.log.txt)
![ubuntu error](https://user-images.githubusercontent.com/103094244/231410924-02bfe6be-4b6d-4f1d-be44-06351043e625.jpg)
![ubuntu error 2](https://user-images.githubusercontent.com/103094244/231411024-7343c3ff-403a-43f8-b7bc-0dc0f380793a.jpg)

**Comment by orangefabri** [comment]
> > > Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> > > Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.
> > 
> > 
> > could I know the airgap server's basic meaning? could I run it on aws server, with similar way for RPI4?
> 
> yes you can. you need aws machine with a domain and that is it.

Today, I discovered an interesting phenomenon.

Until this morning, I had a hard time resolving Andruav's connectivity issue. I tried various solutions, but none of them worked. However, this morning, I successfully connected the video connection using a WiFi.

I connected the drone card to WiFi and was able to send video data multiple times with several reboots. Until now, I had only tried using a WiFi connection with the ground station card and not the drone card.

Unfortunately, the problem remains unresolved since the drone card cannot use WiFi because it will be used at sea. Nevertheless, I hope this discovery will provide a useful clue for solving this issue.

Additionally, I noticed that the red-colored text in the video is not displayed when the video is not sent via LTE. However, I can see "video on" displayed on the drone card's video screen now, with WIFI connection.

Furthermore, the ping is the same as LTE, which leads me to believe that something on the drone card's LTE carrier may be blocking the connection since a WiFi connection was successful.

**Comment by orangefabri** [comment]
> > > Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> > > Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.
> > 
> > 
> > could I know the airgap server's basic meaning? could I run it on aws server, with similar way for RPI4?
> 
> yes you can. you need aws machine with a domain and that is it.

I'm very sorry for too much frequent question.

I solved problem. I turned off some program on laptop and video is received well on laptop.

**Comment by orangefabri** [comment]
> > > Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> > > Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.
> > 
> > 
> > could I know the airgap server's basic meaning? could I run it on aws server, with similar way for RPI4?
> 
> yes you can. you need aws machine with a domain and that is it.

I'm very sorry for too much frequent question.

I solved problem. I turned off some program on laptop and video is received well on laptop.

**Comment by HefnySco** [comment]
If you are operating your own server, you will need to configure the [turnserver address](https://github.com/DroneEngage/droneengage_webclient/blob/95d3d1b8ec8916c13d600772db57acd83e684516/siteConfig.js#L44) to utilize your turnserver that is running on either your airgap or AWS, and ensure that the necessary ports are open. While WVideo can operate on WIFI (local LAN) by utilizing a direct connection, this is not the case when the connection is remote, and a turnserver is utilized instead. Any issues experienced with the connection could be attributed to network, SIM/LTE, or turnserver problems.

**Comment by HefnySco** [comment]
> > > > Please use AirGap Server on local RPI4 and make sure to change the turnserver addess in the webclient.
> > > > Airgap works even without Internet at all you can even cache maps. The video should work then with no problems.
> > > 
> > > 
> > > could I know the airgap server's basic meaning? could I run it on aws server, with similar way for RPI4?
> > 
> > 
> > yes you can. you need aws machine with a domain and that is it.
> 
> I'm very sorry for too much frequent question.
> 
> I solved problem. I turned off some program on laptop and video is received well on laptop.
> 
> I already tried turning off vaccine before, but the problem was force-installed program from my university.

glad to hear that it is working.
