### ISSUE TITLE
Map appears as a white screen.

### ISSUE THREAD

**Issue by orangefabri** [HefnySco/andruav_android_app#9]
Although the telemetry connection is well-established, the map is not displaying properly and appears as a white screen.

**Comment by orangefabri** [comment]
maybe it is related to korean government policy. some of maps are restricted in korea, as far I know.

**Comment by DroneEngage** [comment]
Are you using Andruav_AP not Andruav ?

**Comment by orangefabri** [comment]
> Are you using Andruav_AP not Andruav ?

yes, andruav app only shows web page. we even can't use that.

as the henry's recommendation, I will move to ardupilot web client

**Comment by HefnySco** [comment]
I tested Andruav_AP  GCS map and I found it working. Please note that Andruav_AP uses GoogleMap while WebClient using OpenStreetMap.
You can also download a local server called [Airgap Server](https://youtu.be/ppwuUqomxXY) and have your own mapping server.

**Comment by orangefabri** [comment]
> I tested Andruav_AP GCS map and I found it working. Please note that Andruav_AP uses GoogleMap while WebClient using OpenStreetMap. You can also download a local server called [Airgap Server](https://youtu.be/ppwuUqomxXY) and have your own mapping server.

<- using web client made maps displayable.
